services:
- type: web
  name: superset
  env: docker
  autoDeploy: false
  healthCheckPath: /health
  envVars:
  - key: DATABASE_URL
    value: TBD
#    fromDatabase:
#      name: superset
#      property: connectionString
  - key: PORT
    value: 10000
  - key: SECRET_KEY
    generateValue: true
# databases:
# - name: superset
