services:
- type: web
  name: superset
  env: docker
  autoDeploy: false
  healthCheckPath: /healthz
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: superset
      property: connectionString
  - key: PORT
    value: 10000
  - key: SECRET_KEY
    generateValue: true
databases:
- name: superset
